edition = 1
exports = []

[package]
name = "echo-client-app"
manufacturer = "acme"
description = "Android Echo Client"
authors = []
license = "Apache-2.0"
tags = ["dev", "example", "android"]

[dependencies]
EchoService = { actr_type = "acme:EchoService:1.0.0" }

[signaling]
url = "ws://124.71.231.251:9080/signaling/ws"

[ais_endpoint]
url = "http://124.71.231.251:9080/ais"

[webrtc]
stun_urls = ["stun:124.71.231.251:3487"]
turn_urls = ["turn:124.71.231.251:3487"]
force_relay = false

[deployment]
realm_id = 33554432
realm_secret = "rs_QYhdcomiuyqcF6mb_o3oWain2QAm0QNj"

[discovery]
visible = true

[observability]
filter_level = "info"
tracing_enabled = false

[hyper]
data_dir = "/data/data/io.actorrtc.demo/files/hyper"

[hyper.trust]
kind = "dev_only"

# ACL configuration
[acl]

[[acl.rules]]
permission = "allow"
type = "acme:EchoService:1.0.0"

[[acl.rules]]
permission = "allow"
type = "acme:UnifiedActor:1.0.0"

[scripts]