from __future__ import annotations

from typing import Any, Protocol


class Workload(Protocol):
    def dispatch(self, envelope: Any) -> bytes: ...

    def on_start(self) -> None: ...

    def on_ready(self) -> None: ...

    def on_stop(self) -> None: ...

    def on_error(self, event: Any) -> None: ...

    def on_signaling_connecting(self) -> None: ...

    def on_signaling_connected(self) -> None: ...

    def on_signaling_disconnected(self) -> None: ...

    def on_websocket_connecting(self, event: Any) -> None: ...

    def on_websocket_connected(self, event: Any) -> None: ...

    def on_websocket_disconnected(self, event: Any) -> None: ...

    def on_webrtc_connecting(self, event: Any) -> None: ...

    def on_webrtc_connected(self, event: Any) -> None: ...

    def on_webrtc_disconnected(self, event: Any) -> None: ...

    def on_credential_renewed(self, event: Any) -> None: ...

    def on_credential_expiring(self, event: Any) -> None: ...

    def on_mailbox_backpressure(self, event: Any) -> None: ...
