# Auto-generated by framework_codegen_python. DO NOT EDIT.
from __future__ import annotations

import json
import sys
from typing import Dict, Tuple

from google.protobuf.compiler import plugin_pb2 as plugin

from .generators import generate_local_workload_module


def main() -> int:
    """Main entry point for the protoc plugin."""
    data = sys.stdin.buffer.read()
    request = plugin.CodeGeneratorRequest()
    request.ParseFromString(data)

    parameters = parse_parameters(request.parameter)
    local_files = {
        normalize_proto_path(file)
        for file in parameters.get("LocalFiles", "").split(":")
        if file
    }
    remote_files = {
        normalize_proto_path(file)
        for file in parameters.get("RemoteFiles", "").split(":")
        if file
    }
    remote_file_mapping = parse_mapping(parameters.get("RemoteFileMapping", ""))

    # Build fully-qualified message name -> (package, proto file) map from the
    # full descriptor set so imported RPC message types resolve to their real
    # owner pb2 module instead of the current service's package.
    type_to_owner: dict[str, tuple[str, str, tuple[str, ...]]] = {}
    for file in request.proto_file:
        for message in file.message_type:
            collect_type_owners(file.package, file.name, message, (), type_to_owner)

    response = plugin.CodeGeneratorResponse()
    response.supported_features = plugin.CodeGeneratorResponse.FEATURE_PROTO3_OPTIONAL

    local_services_metadata: list[dict] = []
    remote_services_metadata: list[dict] = []
    for file_name in request.file_to_generate:
        file_desc = next((file for file in request.proto_file if file.name == file_name), None)
        if file_desc is None:
            continue

        normalized_name = normalize_proto_path(file_desc.name)
        role = classify_file(normalized_name, local_files, remote_files)

        if file_desc.service:
            try:
                services_metadata = [
                    build_service_metadata(
                        file_desc.package, normalized_name, service, type_to_owner
                    )
                    for service in file_desc.service
                ]
            except ValueError as error:
                response.error = str(error)
                sys.stdout.buffer.write(response.SerializeToString())
                return 0
            if role == "remote":
                for metadata in services_metadata:
                    actr_type = remote_file_mapping.get(normalized_name)
                    if not actr_type:
                        response.error = (
                            f"No actr_type mapping found for remote file {normalized_name}. "
                            "Use RemoteFileMapping=remote/path.proto=manufacturer:Service."
                        )
                        sys.stdout.buffer.write(response.SerializeToString())
                        return 0
                    metadata["actr_type"] = actr_type
                    metadata["client_type"] = f"{metadata['name']}Client"
                    remote_services_metadata.append(metadata)
            else:
                for metadata in services_metadata:
                    metadata["handler_interface"] = f"{metadata['name']}Handler"
                    metadata["workload_type"] = f"{metadata['name']}Workload"
                    metadata["dispatcher_type"] = f"{metadata['name']}Dispatcher"
                    local_services_metadata.append(metadata)

        if role != "local" or (local_files and normalized_name not in local_files):
            continue

        if not file_desc.service:
            continue

        try:
            generated = generate_local_workload_module(
                file_desc.package,
                normalized_name,
                file_desc.service,
                type_to_owner,
            )
        except NotImplementedError as error:
            response.error = str(error)
            sys.stdout.buffer.write(response.SerializeToString())
            return 0

        out = response.file.add()
        out.name = generated["name"]
        out.content = generated["content"]

    metadata_file = response.file.add()
    metadata_file.name = "actr-gen-meta.json"
    metadata_file.content = json.dumps(
        {
            "plugin_version": "0.4.13",
            "language": "python",
            "local_services": local_services_metadata,
            "remote_services": remote_services_metadata,
        },
        indent=2,
    )

    generated_dirs = set()
    for generated_file in response.file:
        if "/" not in generated_file.name:
            continue
        parts = generated_file.name.split("/")[:-1]
        current = ""
        for part in parts:
            current = f"{current}/{part}" if current else part
            generated_dirs.add(current)

    root_init = response.file.add()
    root_init.name = "__init__.py"
    root_init.content = ""

    for directory in sorted(generated_dirs):
        init_file = response.file.add()
        init_file.name = f"{directory}/__init__.py"
        init_file.content = ""

    sys.stdout.buffer.write(response.SerializeToString())
    return 0


def parse_parameters(param_str: str) -> Dict[str, str]:
    """Parse protoc plugin parameters in key=value format."""
    if not param_str:
        return {}

    params: Dict[str, str] = {}
    for pair in param_str.split(","):
        key, _, value = pair.partition("=")
        params[key] = value
    return params


def parse_mapping(param_str: str) -> Dict[str, str]:
    """Parse semicolon-separated file=actr_type mappings."""
    if not param_str:
        return {}
    mapping: Dict[str, str] = {}
    for item in param_str.split(";"):
        trimmed = item.strip()
        if not trimmed:
            continue
        key, sep, value = trimmed.partition("=")
        if not sep or not key.strip() or not value.strip():
            raise ValueError(f"Invalid RemoteFileMapping entry: {trimmed}")
        mapping[normalize_proto_path(key.strip())] = value.strip()
    return mapping


def classify_file(file_name: str, local_files: set[str], remote_files: set[str]) -> str:
    """Classify a proto file as local or remote from plugin options."""
    normalized = normalize_proto_path(file_name)
    if normalized in remote_files:
        return "remote"
    if normalized in local_files:
        return "local"
    return "remote" if normalized.startswith("remote/") else "local"


def collect_type_owners(
    package_name: str,
    proto_file: str,
    message,
    parents: Tuple[str, ...],
    owners: Dict[str, tuple[str, str, tuple[str, ...]]],
) -> None:
    """Collect fully-qualified message owners, including nested messages."""
    path = (*parents, message.name)
    full_name = ".".join((*([package_name] if package_name else []), *path))
    owners[full_name] = (package_name, normalize_proto_path(proto_file), path)
    for nested in message.nested_type:
        collect_type_owners(package_name, proto_file, nested, path, owners)


def build_service_metadata(
    package_name: str,
    proto_file: str,
    service,
    type_to_owner: Dict[str, tuple[str, str, tuple[str, ...]]],
) -> dict:
    """Build shared ACTR metadata for a protobuf service descriptor."""
    return {
        "name": service.name,
        "package": package_name,
        "proto_file": normalize_proto_path(proto_file),
        "methods": [
            build_method_metadata(
                package_name,
                proto_file,
                service.name,
                method,
                type_to_owner,
            )
            for method in service.method
        ],
    }


def build_method_metadata(
    package_name: str,
    proto_file: str,
    service_name: str,
    method,
    type_to_owner: Dict[str, tuple[str, str, tuple[str, ...]]],
) -> dict:
    """Build shared ACTR metadata for one protobuf RPC method."""
    return {
        "name": method.name,
        "snake_name": to_snake_case(method.name),
        "route_key": make_route_key(package_name, service_name, method.name),
        "input_ref": build_type_ref(
            method.input_type,
            type_to_owner,
            kind="input",
            service_name=service_name,
            method_name=method.name,
            proto_file=proto_file,
        ),
        "output_ref": build_type_ref(
            method.output_type,
            type_to_owner,
            kind="output",
            service_name=service_name,
            method_name=method.name,
            proto_file=proto_file,
        ),
    }


def build_type_ref(
    full_type: str,
    type_to_owner: Dict[str, tuple[str, str, tuple[str, ...]]],
    *,
    kind: str,
    service_name: str,
    method_name: str,
    proto_file: str,
) -> dict:
    """Build a descriptor-owner TypeRef for an RPC input or output."""
    cleaned = full_type.lstrip(".")
    owner = type_to_owner.get(cleaned)
    if owner is None:
        raise ValueError(
            f"Cannot resolve {kind} type `{cleaned}` for {service_name}.{method_name} "
            f"in {normalize_proto_path(proto_file)}: RPC types must be declared "
            "in one of the parsed proto files"
        )
    package_name, proto_file, type_path = owner
    return {
        "proto_type": cleaned,
        "type_name": ".".join(type_path),
        "proto_package": package_name,
        "proto_file": proto_file,
    }


def make_route_key(package_name: str, service_name: str, method_name: str) -> str:
    """Generate a canonical ACTR RPC route key."""
    return (
        f"{package_name}.{service_name}.{method_name}"
        if package_name
        else f"{service_name}.{method_name}"
    )


def normalize_proto_path(value: str) -> str:
    """Normalize a descriptor path for stable cross-language metadata."""
    normalized = value.replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]
    return normalized if normalized.endswith(".proto") else f"{normalized}.proto"


def to_snake_case(name: str) -> str:
    """Convert CamelCase names to snake_case."""
    import re

    normalized = name.replace(".", "_").replace("-", "_")
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", normalized)
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


if __name__ == "__main__":
    raise SystemExit(main())
