"""
Code generation functions for Python actr workload components.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass
class RemoteServiceInfo:
    """Information about a remote service discovered from manifest.lock.toml."""

    service_name: str
    route_keys: List[str]
    actr_type: str


def generate_local_workload_module(
    package_name: str, proto_name: str, services, type_to_owner
) -> dict:
    """Generate typed dispatchers for local protobuf services."""
    proto_module = proto_module_name(proto_name)
    proto_alias = pb2_alias(proto_name)
    file_name = workload_module_name(package_name, services[0].name if services else "workload")

    # Resolve the declaring owner pb2 module for every method input/output type
    # so imported types resolve to their real owner module instead of the
    # current service's package. The alias is derived from the proto file path
    # so two files in the same proto package cannot shadow each other.
    imports: dict[str, str] = {}  # alias -> import line
    imports[proto_alias] = import_line_for(proto_name, proto_module, proto_alias)
    type_refs: dict[str, tuple[str, str]] = {}  # fully-qualified type -> (alias, owner path)

    for service in services:
        for method in service.method:
            for full_type in (method.input_type, method.output_type):
                cleaned = full_type.lstrip(".")
                if cleaned in type_refs:
                    continue
                owner = type_to_owner.get(cleaned)
                if owner is None:
                    type_refs[cleaned] = (proto_alias, extract_message_type(cleaned))
                    continue
                _owner_package, owner_proto_name, owner_type_path = owner
                alias = pb2_alias(owner_proto_name)
                if alias not in imports:
                    imports[alias] = import_line_for(
                        owner_proto_name, proto_module_name(owner_proto_name), alias
                    )
                type_refs[cleaned] = (alias, ".".join(owner_type_path))

    sections: list[str] = [generate_preamble(list(imports.values()))]

    for service in services:
        ensure_no_streaming_methods(service.method)
        sections.append(
            generate_handler_protocol(service.name, service.method, type_refs, proto_alias)
        )
        sections.append(
            generate_dispatcher(
                package_name, service.name, service.method, type_refs, proto_alias
            )
        )

    content = "\n\n".join(section for section in sections if section)
    return {"name": file_name, "content": content}


def generate_preamble(import_lines: list[str]) -> str:
    """Generate module imports."""
    return "\n".join(
        [
            "# DO NOT EDIT.",
            "# Generated by protoc-gen-actrframework-python",
            "from __future__ import annotations",
            "",
            "from typing import Any, Protocol",
            "",
            *import_lines,
        ]
    )


def generate_handler_protocol(
    service_name: str,
    methods,
    type_refs: dict[str, tuple[str, str]],
    default_alias: str,
) -> str:
    """Generate a typed handler protocol for a service."""
    lines: list[str] = [f"class {service_name}Handler(Protocol):"]

    if not methods:
        lines.append("    pass")
        return "\n".join(lines)

    for method in methods:
        method_name = to_snake_case(method.name)
        input_alias, input_type = type_refs.get(
            method.input_type.lstrip("."),
            (default_alias, extract_message_type(method.input_type)),
        )
        output_alias, output_type = type_refs.get(
            method.output_type.lstrip("."),
            (default_alias, extract_message_type(method.output_type)),
        )
        lines.append(
            f"    def {method_name}(self, req: {input_alias}.{input_type}) -> {output_alias}.{output_type}: ..."
        )

    return "\n".join(lines)


def generate_dispatcher(
    package_name: str,
    service_name: str,
    methods,
    type_refs: dict[str, tuple[str, str]],
    default_alias: str,
) -> str:
    """Generate a typed route-key dispatcher for a service."""
    lines: list[str] = [
        f"class {service_name}Dispatcher:",
        f"    def __init__(self, handler: {service_name}Handler):",
        "        self._handler = handler",
        "",
        "    def dispatch(self, envelope: Any) -> bytes:",
        "        route_key = getattr(envelope, \"route_key\", \"\")",
        "        payload = getattr(envelope, \"payload\", b\"\") or b\"\"",
        "",
    ]

    for method in methods:
        route_key = make_route_key(package_name, service_name, method.name)
        method_name = to_snake_case(method.name)
        input_alias, input_type = type_refs.get(
            method.input_type.lstrip("."),
            (default_alias, extract_message_type(method.input_type)),
        )
        output_alias, output_type = type_refs.get(
            method.output_type.lstrip("."),
            (default_alias, extract_message_type(method.output_type)),
        )
        lines.extend(
            [
                f"        if route_key == \"{route_key}\":",
                f"            req = {input_alias}.{input_type}.FromString(bytes(payload))",
                f"            resp = self._handler.{method_name}(req)",
                f"            if not isinstance(resp, {output_alias}.{output_type}):",
                f"                raise TypeError(\"{method_name} must return {output_type}\")",
                "            return resp.SerializeToString()",
                "",
            ]
        )

    lines.append("        raise ValueError(f\"Unknown route_key: {route_key}\")")
    return "\n".join(lines)


def proto_module_name(proto_name: str) -> str:
    """Convert proto file name to module name."""
    filename = proto_name.split("/")[-1]
    base = filename.removesuffix(".proto")
    return f"{base}_pb2"


def pb2_alias(proto_name: str) -> str:
    """pb2 module alias derived from a declaring proto file path."""
    base = (
        proto_name.strip()
        .removesuffix(".proto")
        .replace("/", "_")
        .replace(".", "_")
        .replace("-", "_")
        .lower()
    )
    return f"{base}_pb2" if base else "local_pb2"


def import_line_for(proto_name: str, proto_module: str, proto_alias: str) -> str:
    """Build the `from .<dir> import <module>_pb2 as <alias>` import line."""
    proto_dir = proto_name.rsplit("/", 1)[0] if "/" in proto_name else ""
    proto_dir = proto_dir.replace("-", "_")
    if proto_dir:
        return f"from .{proto_dir.replace('/', '.')} import {proto_module} as {proto_alias}"
    return f"from . import {proto_module} as {proto_alias}"


def workload_module_name(package_name: str, service_name: str) -> str:
    """Return the generated workload dispatcher module path."""
    base = to_snake_case(package_name) if package_name else to_snake_case(service_name)
    return f"{base}_workload.py"


def extract_message_type(full_type: str) -> str:
    """Extract message type name from full type path."""
    return full_type.split(".")[-1]


def to_snake_case(name: str) -> str:
    """Convert CamelCase or dotted names to snake_case."""
    import re

    normalized = name.replace(".", "_").replace("-", "_")
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", normalized)
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def make_route_key(package_name: str, service_name: str, method_name: str) -> str:
    """Generate route key for a method."""
    return f"{package_name}.{service_name}.{method_name}" if package_name else f"{service_name}.{method_name}"


def ensure_no_streaming_methods(methods) -> None:
    """Ensure no streaming methods are present."""
    for method in methods:
        if method.client_streaming or method.server_streaming:
            raise NotImplementedError(
                f"Streaming methods are not supported for Python workloads: {method.name}"
            )
